### ISSUE TITLE
No such file or directory: 'framework/install_scripts/ssh_keys/id_rsa'

### ISSUE THREAD

**Issue by Chenhait** [imperial-qore/SplitPlace#5]
hi, thank you for this wonderful work!!!

however, in your master branch, 
there are no framework and simulator folders.

In addition, run DNN models often use GPU,
but I did not find any infomation about GPU.

I am looking forward your reply!!!
thank you again!

**Comment by shreshthtuli** [comment]
Thanks for your interest in the project. Could you share the command you are running?

**Comment by Chenhait** [comment]
I run the command
python install.py
and when i delete the 98 and 99 lines in install.py
"
for filename in ['id_rsa', 'id_rsa.pub']:
	copy('framework/install_scripts/ssh_keys/'+filename, ssh_dir)
"
It seems worked(I am not sure).

by the way, your videos in COSCO are very useful
and I am looking forward to learning SplitPlace in the video.

best wishes!!!

**Comment by shreshthtuli** [comment]
Thanks. Sit tight for more details and videos!
